stages:
  - build
  - deploy

variables:
  PHP_VERSION: "8.3"

build:
  stage: build
  image: php:$PHP_VERSION-cli
  script:
    - apt-get update -yqq
    - apt-get install -yqq git unzip curl nodejs npm
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-dev --optimize-autoloader
    - npm ci
    - npm run build
    - rm -rf node_modules
    - mkdir -p public/build
    - echo "Build completed successfully"
  artifacts:
    paths:
      - vendor/
      - public/build/
      - bootstrap/
      - storage/framework/
      - .env.example
    expire_in: 1 day

deploy_production:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    
    # Create .htaccess for Zone.ee
    - |
      cat > .htaccess << 'EOF'
      Options +FollowSymLinks -Indexes
      AddType application/x-httpd-php83 .php
      
      RewriteEngine On
      RewriteCond %{REQUEST_URI} !^public
      RewriteRule ^(.*)$ public/$1 [L]
      EOF
    
    # Deploy using rsync
    - |
      rsync -avz --delete \
        --exclude='.git' \
        --exclude='.gitlab-ci.yml' \
        --exclude='node_modules' \
        --exclude='tests' \
        ./ $SSH_USER@$SSH_HOST:/home/romello/rakendused1_new/
    
    # Execute post-deploy commands
    - |
      ssh $SSH_USER@$SSH_HOST "
        cd /home/romello/rakendused1_new && 
        
        # Link shared files
        ln -sf /home/romello/shared/.env .env &&
        ln -sf /home/romello/shared/database/database.sqlite database/database.sqlite &&
        
        # Set up permissions
        chmod -R 775 storage &&
        mkdir -p storage/framework/sessions &&
        mkdir -p storage/framework/views &&
        mkdir -p storage/framework/cache &&
        chmod -R 775 storage/framework/sessions &&
        chmod -R 775 storage/framework/views &&
        chmod -R 775 storage/framework/cache &&
        chmod -R 775 bootstrap/cache &&
        
        # Clear caches
        php artisan optimize:clear &&
        php artisan config:clear &&
        php artisan view:clear &&
        php artisan route:clear &&
        
        # Run migrations
        php artisan migrate --force &&
        
        # Swap directories
        cd /home/romello &&
        if [ -d 'rakendused1' ]; then
          mv rakendused1 rakendused1_old_\$(date +%Y%m%d_%H%M%S)
        fi &&
        mv rakendused1_new rakendused1 &&
        echo 'Deployment complete!'
      "
  only:
    - main
    - master
  environment:
    name: production
    url: https://rakendused1.romello.zone
